name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build_deploy2dockerhub.yml"
      - "modules/Dockerfile.alpine"
      - "nginx.template.conf"
  workflow_dispatch:
    inputs:
      ENABLED_MODULES:
        description: "要编译的 Nginx 模块列表（空格分隔）"
        required: false
        default: "brotli headers-more njs"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Prepare Dockerfile
        run: |
          cp modules/Dockerfile.alpine modules/Dockerfile.temp
          echo 'COPY nginx.template.conf /etc/nginx/nginx.conf' >> modules/Dockerfile.temp
          cp nginx.template.conf modules/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: current_date
        run: echo "current_date=$(TZ=Asia/Shanghai date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: modules
          file: modules/Dockerfile.temp
          push: true
          build-args: |
            NGINX_FROM_IMAGE=nginx:stable-alpine
            ENABLED_MODULES=${{ inputs.ENABLED_MODULES || 'brotli headers-more njs' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{ env.current_date }}
